apiVersion: v1
kind: ConfigMap
metadata:
  name: cataloue
  namespace: roboshop
  labels:
    component: cataloue
    project: roboshop
    tier: app
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cataloue
  namespace: roboshop
  labels:
    component: cataloue
    project: roboshop
    tier: app
spec:
  replicas: 1

  # These are the labels for replica set use to create pod replicas, this should match pod labels 
  selector:
    matchLabels:
      component: cataloue
      project: roboshop
      tier: app
  # This is pod defination
  template:
    metadata:
      labels:
        component: cataloue
        project: roboshop
        tier: app
    spec:
      containers:
      - name: cataloue
        image: joindevops/cataloue:v1
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: cataloue
  namespace: roboshop
  labels:
    component: cataloue
    project: roboshop
    tier: app
spec:
  selector:
    component: cataloue
    project: roboshop
    tier: app
  ports:
  - protocol: TCP
    port: 8080  #service port
    targetPort: 8080 # container port
        
